### PR TITLE
Fix bug with monthly start day > bymonthday

### PR DESCRIPTION
**Pull request by iterion**
I noticed a small issue with the monthly schedule. If the day of the month of the start date was greater than the `BYMONTHDAY` given by the schedule we inadvertently added an extra month to the next occurrence.

This PR fixes that bug and adds a test to prevent regression.

### CODE REVIEW

**Comment by shavz** [comment]
@iterion thanks for checking out the library and taking time to fix an issue. I'll review and merge it soon.

**Comment by iterion** [comment]
:+1: I found another bug, would you prefer a separate PR or just lump them together here?

**Comment by shavz** [comment]
@iterion sorry for the delay and I had a look and its good. Cheers!

Prefer another PR please, rationale is to keep commits as atomic as possible.

**Comment by iterion** [comment]
Absolutely. I created #23 to address some other bugs I found. Thanks for the review and merge. 🙇

**Pull request merged**
